version: "3.9"

services:

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: demo_django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - demo_network
    restart: always

networks:
  demo_network:
    driver: bridge